[book]
title = "Dynamic Memory & Valgrind Debugging"
authors = ["hengvvang"]
description = "Deep dive into dynamic memory allocation, heap leaks, and runtime analysis with Valgrind."
src = "src"

[output.html]
additional-css = ["../../../.theme/custom-mdbook.css"]
additional-js = ["../../../.theme/custom-mdbook.js"]
