[book]
src = "."
title = "C语言动态内存分配、内存泄漏与 Valgrind 排查"
authors = ["hengvvang"]
description = "Compiled Article Book"

[output.html]
additional-css = ["../../../.theme/custom-mdbook.css"]
additional-js = ["../../../.theme/custom-mdbook.js"]
