[book]
title = "FreeRTOS Queue Communication & Thread Safety"
authors = ["hengvvang"]
description = "Exploration of FreeRTOS Queue_t buffer control structures, by-value copy mechanisms, and ISR-safe task communications."
src = "src"
language = "zh-CN"

[output.html]
additional-css = ["../../../shared-theme/custom-mdbook.css"]
additional-js = ["../../../shared-theme/custom-mdbook.js"]
