[book]
title = "Python Magic Methods"
authors = ["hengvvang"]
description = "Deep dive into __new__ vs __init__, operator overloading, container interfaces, custom context managers, and attribute lookup intercepts."
src = "src"

[build]
build-dir = "../../../../public/books/python/oop/dunder_methods"

[output.html]
additional-js = ["../../../__shared_theme/custom-mdbook.js"]
additional-css = ["../../../__shared_theme/custom-mdbook.css"]
smart-punctuation = true
mathjax-support = true
