[book]
title = "Python 常见双下魔术方法与运算符重载"
authors = ["hengvvang"]
description = "Compiled Article Book"
src = "."

[output.html]
additional-css = ["theme/custom-mdbook.css"]
additional-js = ["theme/custom-mdbook.js"]
