[book]
src = "src"
title = "Embedded Linker Scripts & Section Allocation"
authors = ["hengvvang"]
description = "Comprehensive guide to GNU ld linking scripts, MEMORY allocation blocks, sections layout, and loading symbols in C."

[output.html]
additional-css = ["../../../__shared_theme/custom-mdbook.css"]
additional-js = ["../../../__shared_theme/custom-mdbook.js"]
