[book]
title = "Python Basic Decorators"
authors = ["hengvvang"]
description = "Fundamentals of closures, lexical scopes, standard @ syntax wrapping, and generic parameter passing."
src = "src"
language = "zh-CN"

[build]
build-dir = "../../../../public/books/python/decorators/basic_decorators"

[output.html]
additional-js = ["../../../__shared_theme/custom-mdbook.js"]
additional-css = ["../../../__shared_theme/custom-mdbook.css"]
smart-punctuation = true
mathjax-support = true
