[book]
title = "Python Basic Decorators"
authors = ["hengvvang"]
description = "Fundamentals of closures, lexical scopes, standard @ syntax wrapping, and generic parameter passing."
src = "src"
language = "zh-CN"

[output.html]
smart-punctuation = true
mathjax-support = true
