[book]
title = "FreeRTOS High Performance Task Notifications"
authors = ["hengvvang"]
description = "Analysis of TCB-embedded direct task notifications, API operations, and performance comparison to semaphores."
src = "src"

[output.html]
additional-css = ["../../../.theme/custom-mdbook.css"]
additional-js = ["../../../.theme/custom-mdbook.js"]
