import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

// Define the keywords we have
const KEYWORDS: Record<string, string[]> = {
  rust: ['Cargo', 'Rustc', 'Clippy', 'Tokio', 'Wasm'],
  rtos: ['FreeRTOS', 'RT-Thread', 'Zephyr', 'uCOS', 'ThreadX'],
  mcu: ['STM32', 'ESP32', 'GD32', 'MSP430', 'AVR'],
  markup: ['Markdown', 'HTML', 'CSS', 'LaTeX', 'XML'],
  c: ['C99', 'C11', 'Pointer', 'Volatile', 'Makefile'],
  toolchain: ['CMake', 'GCC', 'GDB', 'Git', 'Clang', 'LLVM']
};

// Define candidates / fallbacks for each category and keyword
const slugMapping: Record<string, string[]> = {
  // Category level default icons
  "cat:rust": ["rust"],
  "cat:rtos": ["arm", "riscv", "linux"],
  "cat:mcu": ["arduino", "stmicroelectronics", "espressif"],
  "cat:markup": ["markdown", "html5", "w3c"],
  "cat:c": ["c"],
  "cat:toolchain": ["cmake", "gcc", "llvm", "git"],
  "cat:python": ["python"],

  // Keyword level icons
  "cargo": ["rust"],
  "rustc": ["rust"],
  "clippy": ["eslint", "rust"],
  "tokio": ["tokio", "rust"],
  "wasm": ["webassembly", "w3"],
  "freertos": ["arm", "espressif"],
  "rt-thread": ["arm", "c"],
  "zephyr": ["linux", "linuxfoundation", "arm"],
  "ucos": ["siliconlabs", "nxp", "microchiptechnology", "microchip"],
  "threadx": ["eclipseide", "eclipse", "arm"],
  "stm32": ["stmicroelectronics"],
  "esp32": ["espressif"],
  "gd32": ["riscv", "stmicroelectronics"],
  "msp430": ["arm", "nxp", "texasinstruments"],
  "avr": ["arduino", "microchiptechnology", "microchip"],
  "markdown": ["markdown"],
  "html": ["html5"],
  "css": ["css", "css3"],
  "latex": ["latex"],
  "xml": ["xml", "w3c"],
  "c99": ["c"],
  "c11": ["c"],
  "pointer": ["c"],
  "volatile": ["c"],
  "makefile": ["gnu", "terminal"],
  "cmake": ["cmake"],
  "gcc": ["gcc", "gnu"],
  "gdb": ["gnudebugger", "gnu"],
  "git": ["git"],
  "clang": ["clang", "llvm"],
  "llvm": ["llvm"]
};

const iconsDir = join(__dirname, "node_modules", "simple-icons", "icons");

function findSvg(candidates: string[]): string | null {
  for (const slug of candidates) {
    // Try exact slug
    let filename = `${slug}.svg`;
    let path = join(iconsDir, filename);
    if (existsSync(path)) {
      return readFileSync(path, "utf-8");
    }
    // Try lowercase slug
    filename = `${slug.toLowerCase()}.svg`;
    path = join(iconsDir, filename);
    if (existsSync(path)) {
      return readFileSync(path, "utf-8");
    }
    // Try replacing common symbols
    filename = `${slug.toLowerCase().replace(/[^a-z0-9]/g, "")}.svg`;
    path = join(iconsDir, filename);
    if (existsSync(path)) {
      return readFileSync(path, "utf-8");
    }
  }
  return null;
}

// Clean up SVG: remove xml declaration, doctype, and adjust attributes for styling if needed
function cleanSvg(rawSvg: string): string {
  let cleaned = rawSvg
    .replace(/<\?xml.*?\?>/gs, "")
    .replace(/<!DOCTYPE.*?>/gs, "")
    .trim();
  
  // Make sure it doesn't hardcode width/height so it scales nicely, and can inherit color if fill="currentColor" or fill is present
  // Simple Icons use fill="#HEX". Let's change fill="..." to fill="currentColor" so it behaves like the existing icons (inherits CSS color).
  // Actually, we can replace fill="#[0-9a-fA-F]+" with fill="currentColor".
  cleaned = cleaned.replace(/fill="#[0-9a-fA-F]{3,6}"/g, 'fill="currentColor"');
  
  // Also, add stroke="none" or stroke-width as needed, but simple-icons are paths with fill.
  // Let's ensure it has viewBox="0 0 24 24"
  if (!cleaned.includes("viewBox")) {
    cleaned = cleaned.replace("<svg", '<svg viewBox="0 0 24 24"');
  }
  
  return cleaned;
}

const finalMap: Record<string, string> = {};

// 1. Process category defaults
for (const key of Object.keys(slugMapping)) {
  const candidates = slugMapping[key];
  const svg = findSvg(candidates);
  if (svg) {
    finalMap[key] = cleanSvg(svg);
    console.log(`Matched SVG for ${key} using candidates: ${candidates.join(", ")}`);
  } else {
    console.warn(`WARNING: No SVG matched for ${key}`);
  }
}

// Write the output file
const outputPath = join(__dirname, "src", "icons-data.ts");
const content = `// This file is auto-generated by generate-svg-map.ts. Do not edit directly.
export const SIMPLE_ICONS: Record<string, string> = ${JSON.stringify(finalMap, null, 2)};
`;

import { writeFileSync } from "node:fs";
writeFileSync(outputPath, content, "utf-8");
console.log(`Successfully generated ${outputPath}`);
