[book]
title = "Git Interactive Rebase"
authors = ["hengvvang"]
description = "Manual on merging history, cherry-picking replays, squash/fixup workflows, splitting commits, and conflict resolution."
src = "src"

[output.html]
additional-css = ["../../../__shared_theme/custom-mdbook.css"]
additional-js = ["../../../__shared_theme/custom-mdbook.js"]
