[book]
src = "src"
title = "ESP32 BLE GATT Server Development"
authors = ["hengvvang"]
description = "Deep dive into BLE GATT server architecture, initialization database tables, and callback event processing using ESP-IDF."

[build]
build-dir = "../../../../public/books/mcu/esp32/ble_gatt"

[output.html]
additional-css = ["../../../__shared_theme/custom-mdbook.css"]
additional-js = ["../../../__shared_theme/custom-mdbook.js"]
smart-punctuation = true
mathjax-support = true
