[book]
title = "GCC Compiler Optimizations & Assembly"
authors = ["hengvvang"]
description = "Analysis of GCC compilation optimization options, loop transformations, inlining barriers, and inline assembly constraints."
src = "src"

[output.html]
additional-css = ["../../../shared-theme/custom-mdbook.css"]
additional-js = ["../../../shared-theme/custom-mdbook.js"]
