[book]
src = "."
title = "深入理解 C 语言栈溢出攻击与防御防范"
authors = ["hengvvang"]
description = "Compiled Article Book"

[output.html]
additional-css = ["../../../.theme/custom-mdbook.css"]
additional-js = ["../../../.theme/custom-mdbook.js"]
