[book]
title = "Stack Memory & Overflow Defense"
authors = ["hengvvang"]
description = "Deep dive into calling conventions, function frames, stack overflow vulnerabilities, and defense measures."
src = "src"

[output.html]
additional-css = ["../../../__shared_theme/custom-mdbook.css"]
additional-js = ["../../../__shared_theme/custom-mdbook.js"]
smart-punctuation = true
mathjax-support = true
