[book]
title = "STM32 GPIO Software Simulated I2C Driver"
authors = ["hengvvang"]
description = "Comprehensive guide to I2C physical timing, GPIO simulation, hardware deadlock bugs, and robust driver design."
src = "src"

[output.html]
additional-css = ["../../../__shared_theme/custom-mdbook.css"]
additional-js = ["../../../__shared_theme/custom-mdbook.js"]
