[book]
src = "src"
title = "Zephyr RTOS Devicetree Configuration Decoupling"
authors = ["hengvvang"]
description = "Exploration of Zephyr's Devicetree syntax, bindings matching, compile-time header macro generation, and C API access layers."

[output.html]
additional-css = ["../../../__shared_theme/custom-mdbook.css"]
additional-js = ["../../../__shared_theme/custom-mdbook.js"]
