[book]
title = "Python Metaclasses"
authors = ["hengvvang"]
description = "Exploration of dynamic type construction, custom metaclass compilation, namespace configurations, and real-world validation frameworks."
src = "src"

[output.html]
additional-css = ["../../../__shared_theme/custom-mdbook.css"]
additional-js = ["../../../__shared_theme/custom-mdbook.js"]
