[book]
title = "Python Advanced Decorators"
authors = ["hengvvang"]
description = "Exploration of closures, parameterized class-based decorators, metadata preservation, and dynamic attribute wrapping."
language = "zh-CN"
src = "src"

[output.html]
additional-js = ["../../../__shared_theme/custom-mdbook.js"]
additional-css = ["../../../__shared_theme/custom-mdbook.css"]
smart-punctuation = true
mathjax-support = true
