[book]
title = "Git Flow Workflow"
authors = ["hengvvang"]
description = "Detailed guide to long-lived branch topologies, feature/release/hotfix branching policies, and pull request loops."
src = "src"

[output.html]
additional-js = ["../../../../__shared_theme/custom-mdbook.js"]
additional-css = ["../../../../__shared_theme/custom-mdbook.css"]
smart-punctuation = true
mathjax-support = true
