[book]
title = "CMake 生成静态库与动态库目标规范管理"
authors = ["hengvvang"]
description = "Compiled Article Book"
src = "."

[output.html]
additional-css = ["theme/custom-mdbook.css"]
additional-js = ["theme/custom-mdbook.js"]
