[book]
src = "src"
title = "ESP32 Wi-Fi STA Connection & State Machine"
authors = ["hengvvang"]
description = "Deep dive into Wi-Fi stack configurations, station mode, and event loop state machine handlers under ESP-IDF."

[output.html]
additional-css = ["../../../shared-theme/custom-mdbook.css"]
additional-js = ["../../../shared-theme/custom-mdbook.js"]
