[book]
title = "Markdown Style Guide"
authors = ["hengvvang"]
description = "Manual on typography structures, lists formatting, table alignment, mdBook CSS style overrides, and accessibility."
src = "src"

[output.html]
additional-css = ["../../../shared-theme/custom-mdbook.css"]
additional-js = ["../../../shared-theme/custom-mdbook.js"]
