[book]
title = "Rust Tokio 异步运行时入门与任务调度"
authors = ["hengvvang"]
description = "Compiled Article Book"
src = "."

[output.html]
additional-css = ["theme/custom-mdbook.css"]
additional-js = ["theme/custom-mdbook.js"]
