[book]
title = "CMake Basics & Project Structuring"
authors = ["hengvvang"]
description = "Deep dive into CMake syntax, variables, directory layout management, and CI/CD integration."
src = "src"

[output.html]
smart-punctuation = true
mathjax-support = true
