[book]
title = "Embedded C Memory Layout & Alignment"
authors = ["hengvvang"]
description = "Production-grade guide on memory layout and alignment in embedded systems."

[output.html]
additional-css = ["../../../shared-theme/custom-mdbook.css"]
additional-js = ["../../../shared-theme/custom-mdbook.js"]
