[book]
title = "Zephyr Thread Stack Analyzer & Leakage Debugging"
authors = ["hengvvang"]
description = "Complete manual on monitoring thread stack watermarks, arming stack protectors (MPU/Canary), and debugging dynamic heap leaks."
language = "zh-CN"

[output.html]
additional-js = ["../../../__shared_theme/custom-mdbook.js"]
additional-css = ["../../../__shared_theme/custom-mdbook.css"]
smart-punctuation = true
mathjax-support = true
