[book]
authors = ["hengvvang"]
description = "In-depth guide to Python event loops, native coroutines, asyncio task concurrency, and thread execution integration."
src = "src"
title = "Python asyncio"

[build]
build-dir = "../../../../public/books/python/concurrency/asyncio_basics.html"

[output.html]
additional-js = ["../../../__shared_theme/custom-mdbook.js"]
additional-css = ["../../../__shared_theme/custom-mdbook.css"]
smart-punctuation = true
mathjax-support = true
