[book]
title = "Rust Lifetime Fundamentals"
authors = ["hengvvang"]
description = "Introduction to Rust lifetimes, reference scopes, borrow checker rules, struct lifetime annotation, and lifetime elision rules."
src = "src"

[output.html]
additional-css = ["../../../.theme/custom-mdbook.css"]
additional-js = ["../../../.theme/custom-mdbook.js"]
