[book]
title = "Git Flow Workflow"
authors = ["hengvvang"]
description = "Detailed guide to long-lived branch topologies, feature/release/hotfix branching policies, and pull request loops."
src = "src"

[output.html]
additional-css = ["../../../.theme/custom-mdbook.css"]
additional-js = ["../../../.theme/custom-mdbook.js"]
