[book]
src = "src"
title = "Git Reflog"
authors = ["hengvvang"]
description = "Low-level guide to Git HEAD reference changes logs, recovering dangling commits, reset safety, and reflog expiration policies."

[output.html]
additional-js = ["../../../../__shared_theme/custom-mdbook.js"]
additional-css = ["../../../../__shared_theme/custom-mdbook.css"]
smart-punctuation = true
mathjax-support = true
