[book]
title = "C语言数组指针与指针数组概念辨析"
authors = ["hengvvang"]
description = "Compiled Article Book"
src = "."

[output.html]
additional-css = ["theme/custom-mdbook.css"]
additional-js = ["theme/custom-mdbook.js"]
