[book]
title = "Git Trunk Based Development"
authors = ["hengvvang"]
description = "Exploration of Trunk-Based continuous integration, Feature Flags decoupling, branch-by-abstraction, and deployment pipelines."
language = "zh-CN"

[output.html]
additional-css = ["../../../__shared_theme/custom-mdbook.css"]
additional-js = ["../../../__shared_theme/custom-mdbook.js"]
