[book]
title = "Callback Mechanisms, Function Pointers & OOP C"
authors = ["hengvvang"]
description = "Deep dive into function pointers, callback architectures, and OOP design patterns in C."
src = "src"

[output.html]
additional-css = ["../../../shared-theme/custom-mdbook.css"]
additional-js = ["../../../shared-theme/custom-mdbook.js"]
