[book]
title = "CMake Embedded Cross Compilation"
authors = ["hengvvang"]
description = "Deep dive into cross compilation toolchain files, MCU targets, and bare-metal compilation with CMake."
src = "src"

[output.html]
additional-js = ["../../../__shared_theme/custom-mdbook.js"]
additional-css = ["../../../__shared_theme/custom-mdbook.css"]
smart-punctuation = true
mathjax-support = true
