[book]
title = "Rust Multi-Threaded Concurrency"
authors = ["hengvvang"]
description = "Exploration of OS thread creation, scoped tasks, Send/Sync properties, Arc/Mutex layouts, and message channels."
language = "zh-CN"
src = "src"


[output.html]
additional-css = ["../../../shared-theme/custom-mdbook.css"]
additional-js = ["../../../shared-theme/custom-mdbook.js"]
